[package]
name = "faa-nasr-data-processor"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
menu_genie = "0.1.1"